services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    env_file: ./gateway/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  customer:
    build: ./customer
    env_file: ./customer/.env
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672

  product:
    build: ./product
    env_file: ./product/.env
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672

  shopping:
    build: ./shopping
    env_file: ./shopping/.env
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
