services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    env_file: ./gateway/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  customer:
    build: ./customer
    env_file: ./customer/.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672

  product:
    build: ./product
    env_file: ./product/.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672

  shopping:
    build: ./shopping
    env_file: ./shopping/.env
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
